### ISSUE TITLE
Some improvements suggestions

### ISSUE THREAD

**Issue by elibyy** [naomik/htmlgen#6]
1. Auto generate DOCTYPE
2. Limit creation of elements to an array of existing elements by array.
3. Limit the attributes to an element by array.
4. Allow generation of start or end tag only, so if you templating you will have the possibility to have head.php and etc.
5. Some ApiGen comments so the code will be more readable.
6. Validation of total output via w3 validator.

**Comment by beeelze** [comment]
@naomik You should keep working on it. I really like projects like this :-)

**Comment by naomik** [comment]
@beeelze thank you for your feedback. I've been stuck having to write some PHP lately, so maybe I will resurrect this project after all ...

**Comment by naomik** [comment]
@elibyy and @beeelze thanks for remaining patient. As if y'all we're waiting around, right? ^_^

[2.0.0-pre](https://github.com/naomik/htmlgen/tree/2.0.0) was just pushed

Here's a sort of chaneglog... of sorts...

* All the magic is gone
* It's just pure PHP with no funny business.
* Templating via native PHP `require` (see the provided example)
* Syntax is roughly the same, but much nicer
* Code base is 60% smaller
* Output buffering is gone
* View helpers like `h::cycle` are gone
* Data store is no longer necessary. `set_variable` and `get_variable` are gone
* Pretty printing is out (at least for now)

I'll keep everyone updated with progress and a final 2.0 release

I still want to add some unit tests.

**Comment by naomik** [comment]
@elibyy, @beeelze 

[Version 2.0](https://github.com/naomik/htmlgen) released just now

Any feedback is appreciated. If you have problems, please open a new issue.

Thanks for your support and patience.
