### ISSUE TITLE
About passing globals (how to "make awesome")

### ISSUE THREAD

**Issue by AndruxaSazonov** [naomik/htmlgen#8]
This code:

```php
h::table(function(){
        # sadly, i'm not sure how to get around this at the moment :(  help me make this awesome
        global $table_data;
//...
```

possibly it could have overloaded variant? Such as

```php
h::table(function($context_class_object_containing_globals) { 
//...
```

or 

```php
h::table($context, function() {
///...
```

??

**Comment by AndruxaSazonov** [comment]
And many thanks to you and yours htmlgen! It's a charm! :)

**Comment by naomik** [comment]
That's an interesting idea. I didn't think I'd ever work on this project again, but now that I'm doing more PHP work lately, I might pick it back up. Don't get too excited, but I'll keep you updated on any progress !

**Comment by naomik** [comment]
@AndruxaSazonov OK, I suppose your request prompted me to rewrite the whole damned thing. I think you'll be very pleased with the results.

Check out [2.0.0-pre](https://github.com/naomik/htmlgen/tree/2.0.0).

Here's a sort of chaneglog... of sorts...

* All the magic is gone
* It's just pure PHP with no funny business.
* Templating via native PHP `require` (see the provided example)
* Syntax is roughly the same, but much nicer
* Code base is 60% smaller
* Output buffering is gone
* View helpers like `h::cycle` are gone
* Data store is no longer necessary. `set_variable` and `get_variable` are gone
* Pretty printing is out (at least for now)

I'll let you know once `2.0` is live and stable. I still want to add some unit tests. I'll get to it over the next day or two.

**Comment by avsazonov** [comment]
Surpsingly exciting!.. Thanks for your rework!

**Comment by naomik** [comment]
@AndruxaSazonov, @avsazonov 

[Version 2.0](https://github.com/naomik/htmlgen) released just now

Any feedback is appreciated. If you find issues, please create a new issue.
